Temperature Screen
arctouch-vivyanrodrigues/arcweather-flutter pull request #13
Opened 2021-07-28 17:44 UTC by arctouch-vivyanrodrigues

**Description**
- [x] Create the Temperature screen with the Background Image
- [x] Text: "Choose your preferred temperature scale:"
- [x] Radiobutton-like options for Celsius or Fahrenheit:
- [x] The Celsius button should be already selected at the beginning. 
- [x] There should be always a selected button.
- [x] Next button - Persist the user's option.
- [x] Next button - By tapping on it the app should display the Location Screen.
- [x] Next button - If the user goes to the next screen and closes the app, this screen should not appear anymore.

**Ticket**
- AWE-21 - Temperature Screen

**Demo**

**iPhone 8:**
![iphone8](https://user-images.githubusercontent.com/86257896/127371037-7087c32b-1ed7-47a0-b672-4daf90d35a0d.gif)

**iPhone 12:**
![iphone12](https://user-images.githubusercontent.com/86257896/127371042-bd858249-59f0-40b5-bc8a-c004b5019df8.gif)

**Android:**
![android](https://user-images.githubusercontent.com/86257896/127371048-3eb593aa-f385-4ebd-a3db-8577c612357d.gif)

2021-07-28 18:14 UTC, arctouch-victorbotamedi requested changes
Awesome work. 

I did some nit pickings ;) 

The more important stuff we need to take a look at here:
* TemperatureRatio has a ton of unnecessary wrapped widgets.
* Using a router (or Navigator 2.0 if you want to) to do navigation.
* i18n

And the most important, lets start writing unit tests :)

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/components/temperature_ratio.dart
> +      child: Container(
The proper widget to use here is the `SizedBox`. We should avoid using heavy widgets wherever we can use more lightweight widgets that serve a single purpose.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/components/temperature_ratio.dart
> +            _customRadioButton,
probably this whole container is not needed, you already return a full container from this method...

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/components/temperature_ratio.dart
> +  Widget get _customRadioButton {
This should be a method.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/constants/constants.dart
> +const kTemperatureRoute = 'temperature';
We should split the constant files, you already have one for images, now you can have one for routes, colors and styles, although usually styles should be set on your app's theme.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/controller/controller_temperature.dart
> +class Controller = ControllerTemperature with _$Controller;
Can we remove this? This is going to be a hell to manage in the future, since we already have a definition for `Controller` in the project. You can use something like `class ControllerTemperature = _ControllerTemperature with _$Controller;`. This way it is easy to find references and track down usage.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/main.dart
> +    initialRoute = kTemperatureRoute;
We should have unit tests for this. This is a testable business logic, it can be extracted to a service of some sorts.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +import 'temperature_screen.dart';
Use `package` imports.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +      Navigator.push(context,
I wondering why we have routes constants.

I believe you want to do navigation using routes, so you probably want to implement a router and remove all page constructions from inside other pages.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/temperature_screen.dart
> +          child: Padding(
The parent container has a Padding property.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/temperature_screen.dart
> +                  'Choose your preferred temperature scale:',
Can we add i18n now? As the project grows it will be harder and harder to trace back all text usages.

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/temperature_screen.dart
> +                Padding(
You can use a SizedBox with height: 20 to do this margin

2021-07-28 18:14 UTC, arctouch-victorbotamedi commented on lib/screens/temperature_screen.dart
> +                Padding(
Same.

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/temperature_screen.dart
> +                Padding(
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/temperature_screen.dart
> +                Padding(
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/temperature_screen.dart
> +          child: Padding(
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +      Navigator.push(context,
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +import 'temperature_screen.dart';
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/main.dart
> +    initialRoute = kTemperatureRoute;
Done!

2021-07-28 19:15 UTC, arctouch-vivyanrodrigues commented on lib/constants/constants.dart
> +const kTemperatureRoute = 'temperature';
Done!

2021-07-28 19:16 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +  Widget get _customRadioButton {
Done!

2021-07-28 19:16 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +            _customRadioButton,
Done!

2021-07-28 19:16 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +      child: Container(
Done!

2021-07-28 19:16 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +        child: Row(
Done!

2021-07-28 22:37 UTC, arctouch-vivyanrodrigues commented on lib/controller/controller_temperature.dart
> +class Controller = ControllerTemperature with _$Controller;
Done!

2021-07-30 14:49 UTC, arctouch-vivyanrodrigues commented on lib/main.dart
> +    initialRoute = kTemperatureRoute;
Done!

2021-07-30 14:49 UTC, arctouch-vivyanrodrigues commented on lib/screens/temperature_screen.dart
> +                  'Choose your preferred temperature scale:',
We're going to do in a seperate ticket

2021-07-30 17:16 UTC, arctouch-vivyanrodrigues commented on lib/constants/route_constants.dart
> +const kInitialRoute = kOnboardRoute;
Done!

2021-07-30 17:17 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +    return InkWell(
Done!

2021-07-30 17:20 UTC, arctouch-vivyanrodrigues commented on lib/components/temperature_ratio.dart
> +          color: isSelected ? Color(0xFF2F72BB) : Color(0xFFFFFFFF),
Done!

2021-07-30 17:21 UTC, arctouch-vivyanrodrigues commented on lib/screens/temperature_screen.dart
> +class _TemperatureScreenState extends State<TemperatureScreen> {
Done!

2021-07-30 17:37 UTC, arctouch-victorbotamedi approved these changes

2021-07-30 17:38 UTC, merged