Location Screen
arctouch-vivyanrodrigues/arcweather-flutter pull request #14
Opened 2021-07-30 21:29 UTC by arctouch-vivyanrodrigues

2021-08-03 17:29 UTC, arctouch-victorbotamedi commented on test/router_test.dart
> +      when(preferencesService.completedTemperature).thenAnswer((_) => true);
since those are not `Future`, you don't need to use `thenAnswer`. Tou should use `thenReturn(true)` instead

2021-08-03 20:31 UTC, arctouch-victorbotamedi requested changes

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/constants/image_constants.dart
> +final kArrowNextButton = SvgPicture.asset("assets/icons/arrow_next.svg");
I just noticed this, but you should store only the path here as a constant  `static const kArrowNextButton = "assets/icons/arrow_next.svg"`.

By having a `SvgPicture.asset` and `AssetImage`, you are essentially creating a widget here, storing a ton of unnecessary information for this specific context.

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/screens/location_screen.dart
> +          padding: EdgeInsets.only(right: 23.0, left: 23.0),
You can use `EdgeInsets.symmetric(horizontal: 23.0),`

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/screens/location_screen.dart
> +                    onTap: () =>
Use `Navigator.pop`, otherwise you are stacking a new page on the navigation stack.
Probably on Android if you tab the back button you can go back 3 times by doing this.

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/screens/location_screen.dart
> +                GestureDetector(
This has to be a button. 
You can either implement your own, or style the Flutter button widget. 

I say this because other places on the app use it, also the temperature uses the exact same button. 
So essentially, it is a button widget that you can re use throughout the app.

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  OnboardingStore? _onboardingStore;
You know this is going to be initialized. So you can use the `late` keyword here. This way you won't need to check nullability everywhere.

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/stores/temperature_store.dart
> +    if (!discOnly) {
This `discOnly` property doesn't seem to be used.

2021-08-03 20:31 UTC, arctouch-victorbotamedi commented on lib/stores/temperature_store.dart
> +  void changeIndex(int? val) => temperatureValue = val!;
You are never storing the chosen temperature units, how are you going to access it on the main screen?

2021-08-03 22:00 UTC, arctouch-vivyanrodrigues commented on test/router_test.dart
> +      when(preferencesService.completedTemperature).thenAnswer((_) => true);
that's weird, here I did the change...

2021-08-03 22:00 UTC, arctouch-vivyanrodrigues commented on test/router_test.dart
> +      when(preferencesService.completedTemperature).thenAnswer((_) => true);
Done!

2021-08-03 22:05 UTC, arctouch-vivyanrodrigues commented on lib/constants/image_constants.dart
> +final kArrowNextButton = SvgPicture.asset("assets/icons/arrow_next.svg");
Done!

2021-08-03 22:05 UTC, arctouch-vivyanrodrigues commented on lib/screens/location_screen.dart
> +          padding: EdgeInsets.only(right: 23.0, left: 23.0),
Done!

2021-08-03 22:09 UTC, arctouch-vivyanrodrigues commented on lib/screens/location_screen.dart
> +                    onTap: () =>
Done!

2021-08-03 22:10 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +  OnboardingStore? _onboardingStore;
Done!

2021-08-04 14:47 UTC, arctouch-vivyanrodrigues commented on lib/screens/location_screen.dart
> +                GestureDetector(
Done!

2021-08-04 14:49 UTC, arctouch-vivyanrodrigues commented on lib/stores/temperature_store.dart
> +    if (!discOnly) {
Done!

2021-08-04 17:05 UTC, arctouch-vivyanrodrigues commented on lib/stores/temperature_store.dart
> +  void changeIndex(int? val) => temperatureValue = val!;
Done!

2021-08-04 18:41 UTC, arctouch-victorbotamedi commented on lib/components/location_button.dart
> +class locationButton extends StatelessWidget {
Please make a generic button so you can reuse it through the app. 
You can pass an `onPressed` and `text` properties in the constructor.

Also, classes should start with a capital letter.

2021-08-04 18:53 UTC, arctouch-vivyanrodrigues commented on lib/components/location_button.dart
> +class locationButton extends StatelessWidget {
Done!

2021-08-05 14:27 UTC, arctouch-victorbotamedi reviewed
Small comments to wrap up

2021-08-05 14:27 UTC, arctouch-victorbotamedi commented on lib/components/arcweather_button.dart
> +        constraints: BoxConstraints.tightFor(width: 264),
The button widget has a constraints property. But this is fine too.

2021-08-05 14:27 UTC, arctouch-victorbotamedi commented on lib/screens/location_screen.dart
> +                  onPress: () {
Can be an arrow function

2021-08-05 14:39 UTC, arctouch-vivyanrodrigues commented on lib/components/arcweather_button.dart
> +    return ElevatedButton(
Done!

2021-08-05 14:51 UTC, arctouch-vivyanrodrigues commented on lib/screens/location_screen.dart
> +                  onPress: () {
Done!

2021-08-05 15:16 UTC, arctouch-victorbotamedi approved these changes

2021-08-05 15:22 UTC, merged