Create a widget for Slider Widget
arctouch-vivyanrodrigues/arcweather-flutter pull request #5
Opened 2021-07-06 21:42 UTC by arctouch-vivyanrodrigues

2021-07-08 14:42 UTC, arctouch-victorbotamedi requested changes
The `pubspeck.lock` should be on gitignore.

Also, you didn't add the x2, x3 versions of the images, make sure to add those.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/components/page_index_indicator.dart
> +          color: isCurrentPage ? Color(0xFFFFFFFF) : Color(0x40000000),
We can have a constant colors file to keep those

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/components/slider_box.dart
> +          SizedBox(
Can be one `SizedBox` with height of `40`

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/components/slider_box.dart
> +                  fontFamily: 'Avenir Light',
Please set the font family on the app theme.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/models/slider_model.dart
> +  String getImagePath(){
It is not a good practice in dart to have `getSomething` and `setSomething`. The language provides those features

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/models/slider_model.dart
> +List<SliderModel> getSlides() {
It is not really getting something, it is building the list. So the `buildSlideList` would be more appropriate.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/controller/controller_slider.dart
> +abstract class ControllerSlider with Store {
We still have to figure out if UI states that doesn't have business rules should be handled by mobx.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/home_screen.dart
> +class HomeScreen extends StatelessWidget {
Modern flutter navigators use the `MaterialPage` nomenclature. So it would be nicer if we keep the same standard and call it `HomePage`.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/home_screen.dart
> +  Widget build(BuildContext context) {
You can use an expression function here.
```
Widget build(BuildContext context) => Scaffold(
  backgroundColor: Colors.black,
);
```

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  Controller controller = Controller();
Can be final

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  PageController pageController = PageController(initialPage: 0);
can be final

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +            image: AssetImage("images/bgOnboarding.jpg"),
We can move this to an image constants file

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +              SafeArea(
This `SafeArea` widget can be the first of the tree

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +                            SizedBox(
This `SizedBox` can be outside the page view. So you don't need an extra `Column` here

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +                onTap: () {
You can extract the button tap logic to a function.

2021-07-08 14:42 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +                      ? "Next >"
The `>`, is not a character in the designs, it is an icon. Please use the zeplin resource instead.

2021-07-08 20:42 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +              SafeArea(
Acabei reorganizando o código e não precisou desse widget, resolvi com Padding.

2021-07-08 21:28 UTC, arctouch-vivyanrodrigues commented on lib/controller/controller_slider.dart
> +abstract class ControllerSlider with Store {
I've talked to Romão and he said that usually he doesn't use setState, and I could use MobX with no problem.

2021-07-08 21:42 UTC, arctouch-vivyanrodrigues commented on lib/components/page_index_indicator.dart
> +          color: isCurrentPage ? Color(0xFFFFFFFF) : Color(0x40000000),
Done!

2021-07-08 21:42 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_box.dart
> +          SizedBox(
Done!

2021-07-08 21:42 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_box.dart
> +                  fontFamily: 'Avenir Light',
Done!

2021-07-08 21:43 UTC, arctouch-vivyanrodrigues commented on lib/models/slider_model.dart
> +  String getImagePath(){
What do you recommend, then?

2021-07-08 21:43 UTC, arctouch-vivyanrodrigues commented on lib/models/slider_model.dart
> +List<SliderModel> getSlides() {
Done!

2021-07-08 21:43 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +            image: AssetImage("images/bgOnboarding.jpg"),
Done!

2021-07-08 21:43 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +                            SizedBox(
Done!

2021-07-08 21:43 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +                onTap: () {
Done!

2021-07-09 16:20 UTC, arctouch-vivyanrodrigues commented on lib/models/slider_model.dart
> +  String getImagePath(){
Done!

2021-07-09 16:35 UTC, arctouch-victorbotamedi commented on lib/models/slider_model.dart
> +  String imagePath;
mark these as `final` and remove all getters

2021-07-09 18:24 UTC, arctouch-victorbotamedi approved these changes
Awesome looks good.
Added some nice to have changes.

2021-07-09 18:24 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  void nextPageButton() {
NTH: this can be private `_nextPageButton`

2021-07-09 18:24 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  Widget build(BuildContext context) {
NTH: the standard style is to have the public methods first, so this should be up top before any private method.

2021-07-09 18:42 UTC, merged