Bounce
arctouch-vivyanrodrigues/arcweather-flutter pull request #9
Opened 2021-07-19 20:49 UTC by arctouch-vivyanrodrigues

2021-07-22 16:28 UTC, arctouch-victorbotamedi requested changes

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/components/slider_illustration.dart
> +    return Align(
It is better to leave this align on the parent widget. It is better for the parent component to align things properly, otherwise if you want to use this widget anywhere else you would have a messed alignment.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/components/slider_text.dart
> +    return Align(
Same.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/components/slider_text.dart
> +      child: SizedBox(
Sized boxes wrapping texts usually is not a good thing. Think that all devices have an accessibility mode with huge fonts, if you have a fixed size for the text box, then the text may be cut. In this case, you have plenty of space for the text to grow, so I would recommend to not have a sized box here.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/components/slider_text.dart
> +              child: Container(
Same here, you don't need this container.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/constants/constants.dart
> +const kOnboardingCurve = Cubic(0.175, 0.885, 1.0, 1.1);
This is used only by the onboard. There is no reason to be in a publicly accessible place.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +        AnimationController(vsync: this, duration: Duration(seconds: 2));
The entry animation looks super slow, it has to be way faster.

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  void _delayedFollowScroll(double offset) {
This can be an arrow function

2021-07-22 16:28 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  Widget _buildNextButton() {
This can be an arrow function

2021-07-22 18:34 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +  Widget _buildNextButton() {
Done!

2021-07-22 18:34 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +  void _delayedFollowScroll(double offset) {
Done!

2021-07-22 18:34 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +        AnimationController(vsync: this, duration: Duration(seconds: 2));
Done!

2021-07-22 18:35 UTC, arctouch-vivyanrodrigues commented on lib/constants/constants.dart
> +const kOnboardingCurve = Cubic(0.175, 0.885, 1.0, 1.1);
Done!

2021-07-22 18:35 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_text.dart
> +              child: Container(
Done!

2021-07-22 18:35 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_text.dart
> +      child: SizedBox(
Done!

2021-07-22 21:40 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_illustration.dart
> +    return Align(
done!

2021-07-22 21:40 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_text.dart
> +    return Align(
Done!

2021-07-23 14:10 UTC, arctouch-victorbotamedi commented on lib/components/slider_illustration.dart
> +    return Column(
This `Column` is not needed. Tou can use the align property of `Image.asset`

2021-07-23 14:10 UTC, arctouch-victorbotamedi commented on lib/components/slider_illustration.dart
> +  Widget build(BuildContext context) {
Can be an arrow function

2021-07-23 14:11 UTC, arctouch-victorbotamedi commented on lib/components/slider_text.dart
> +    return SizedBox(
Again, this sized box has to go

2021-07-23 14:11 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  static const onboardingCurve = Cubic(0.175, 0.885, 1.0, 1.1);
styling: constant values should be the first thing in the class

2021-07-23 14:13 UTC, arctouch-victorbotamedi commented on lib/screens/onboarding_screen.dart
> +  Widget build(BuildContext context) {
Can be an arrow function

2021-07-23 16:15 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_illustration.dart
> +    return Column(
Done!

2021-07-23 16:15 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_illustration.dart
> +  Widget build(BuildContext context) {
Done!

2021-07-23 16:15 UTC, arctouch-vivyanrodrigues commented on lib/components/slider_text.dart
> +    return SizedBox(
Done!

2021-07-23 16:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +  static const onboardingCurve = Cubic(0.175, 0.885, 1.0, 1.1);
Done!

2021-07-23 16:15 UTC, arctouch-vivyanrodrigues commented on lib/screens/onboarding_screen.dart
> +  Widget build(BuildContext context) {
Done!

2021-07-23 18:44 UTC, arctouch-victorbotamedi approved these changes

2021-07-23 18:45 UTC, merged